#define ALDOS         0
#define ALPINE        1
#define ANTERGOS      2
#define ARCH_OLD      3
#define ARCH          4
#define ARTIX         5
#define ARYA          6
#define BLAG          8
#define BLANK_ON      9
#define BSD           10
#define BUNSEN_LABS   11
#define BLACK_PANTHER 12
#define CALCULATE     13
#define CENT_OS       14
#define CHAKRA        15
#define CHALET_OS     16
#define CHAPEAU       17
#define CHROM         18
#define CLEAR_OS      19
#define CLOVER        20
#define CONDRES       21
#define CRUX          22
#define DEBIAN        23
#define DEEPIN        24
#define DESA_OS       25
#define DEVUAN        26
#define DRAC_OS       27
#define DRAGONFLY_OLD 28
#define DRAGONFLY     29
#define ELEMENTARY    30
#define ENDLESS       31
#define EXHERBO       32
#define FEDORA        33
#define FREE_BSD      34
#define FRUGALWARE    35
#define FUNTOO        36
#define GALLIUM_OS    37
#define GENTOO        38
#define GNEWSENSE     39
#define GNU           40
#define GOBO          41
#define GROMBYANG     42
#define GUIXSD        43
#define HAIKU         44
#define HYPERBOLA     45
#define JANUS         46
#define KALI          47
#define KA_OS         48
#define KDE           49
#define KIBOJOE       50
#define KOGAION       51
#define KORORA        52
#define KS            53
#define KUBUNTU       54
#define LEDE          55
#define LINUX         56
#define LINUX_LITE    57
#define LMDE          58
#define LUBUNTU       59
#define LUNAR         60
#define MAGEIA        61
#define MAGPIE_OS     62
#define MANDRIVA      63
#define MANJARO       64
#define MAUI          65
#define MER           66
#define MINIX         67
#define MINT          68
#define MX            69
#define NAMIB         70
#define NET_BSD       71
#define NETRUNNER     72
#define NITRUX        73
#define NIX_OS        74
#define NURUNNER      75
#define NUTYX         76
#define OBREVENGE     77
#define OPEN_BSD      78
#define OPEN_INDIANA  79
#define OPEN_MANDRIVA 80
#define OPEN_WRT      81
#define OSMC          82
#define ORACLE        83
#define PAC_BSD       84
#define PARABOLA      85
#define PARDUS        86
#define PARROT        87
#define PARSIX        88
#define PC_BSD        89
#define PEPPERMINT    90
#define POP_OS        91
#define PORTEUS       92
#define POSTMARKET_OS 93
#define PUPPY         94
#define PURE_OS       95
#define QUBES         96
#define RASPBIAN      97
#define REBORN_OS     98
#define RED_STAR      99
#define REDCORE       100
#define REDHAT        101
#define REGATA        102
#define ROSA          103
#define SABOTAGE      104
#define SABAYON       105
#define SAILFISH_OS   106
#define SALENT_OS     107
#define SCIENTIFIC    108
#define SHARK         109
#define SIDUCTION     110
#define SLACKWARE     110
#define SLITAZ        111
#define SMART_OS      112
#define SOLUS         113
#define SOURCE_MAGE   114
#define SPARKY        115
#define STEAM_OS      116
#define SUN_OS        117
#define OPENSUSE_TUMBLEWEED 118
#define OPENSUSE      118
#define SWAG_ARCH     119
#define TAILS         120
#define TRISQUEL      121
#define UBUNTU_BUDGIE 122
#define UBUNTU_GNOME  123
#define UBUNTU_MATE   124
#define UBUNTU_OLD    125
#define UBUNTU_STUDIO 126
#define UBUNTU        127
#define VOID          128
#define XUBUNTU       129
#define ZORIN         130



#define DEFAULT "\e[39m"
#define BLACK   "\e[30m"
#define WHITE   "\e[97m"
#define RED     "\e[31m"
#define GREEN   "\e[32m"
#define YELLOW  "\e[33m"
#define BLUE    "\e[34m"
#define MAGENTA "\e[35m"
#define CYAN    "\e[36m"

#define LIGHT_GRAY    "\e[37m"
#define DARK_GRAY     "\e[90m"
#define LIGHT_RED     "\e[91m"
#define LIGHT_GREEN   "\e[92m"
#define LIGHT_YELLOW  "\e[93m"
#define LIGHT_BLUE    "\e[94m"
#define LIGHT_MAGENTA "\e[95m"
#define LIGHT_CYAN    "\e[96m"


#define BG_LIGHT_RED     "\e[101m"
#define BG_LIGHT_GREEN   "\e[102m"
#define BG_LIGHT_YELLOW  "\e[103m"
#define BG_LIGHT_BLUE    "\e[m"
#define BG_LIGHT_MAGENTA "\e[m"
#define BG_LIGHT_CYAN    "\e[m"
#define BG_LIGHT_GRAY    "\e[m"
#define BG_WHITE         "\e[m"

#define BG_DEFAULT   "\e[49m"
#define BG_BLACK     "\e[40m"
#define BG_RED       "\e[41m"
#define BG_GREEN     "\e[42m"
#define BG_YELLOW    "\e[43m"
#define BG_BLUE      "\e[44m"
#define BG_MAGENTA   "\e[45m"
#define BG_CYAN      "\e[46m"
#define BG_DARK_GRAY "\e[100m"
